insert ALL
 into glocation values(0,'		','		')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','		')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	종로구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	중구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	용산구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	성동구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	광진구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	동대문구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	중랑구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	성북구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	강북구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	도봉구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	노원구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	은평구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	서대문구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	마포구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	양천구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	강서구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	구로구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	금천구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	영등포구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	동작구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	관악구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	서초구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	강남구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	송파구	')
 into glocation values(glocationSEQ.nextval,'	서울특별시	','	강동구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','		')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	중구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	서구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	동구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	영도구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	부산진구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	동래구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	남구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	북구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	해운대구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	사하구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	금정구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	강서구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	연제구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	수영구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	사상구	')
 into glocation values(glocationSEQ.nextval,'	부산광역시	','	기장군	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','		')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	중구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	동구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	서구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	남구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	북구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	수성구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	달서구	')
 into glocation values(glocationSEQ.nextval,'	대구광역시	','	달성군	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','		')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	중구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	동구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	미추홀구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	연수구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	남동구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	부평구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	계양구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	서구	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	강화군	')
 into glocation values(glocationSEQ.nextval,'	인천광역시	','	옹진군	')
 into glocation values(glocationSEQ.nextval,'	광주광역시	','		')
 into glocation values(glocationSEQ.nextval,'	광주광역시	','	동구	')
 into glocation values(glocationSEQ.nextval,'	광주광역시	','	서구	')
 into glocation values(glocationSEQ.nextval,'	광주광역시	','	남구	')
 into glocation values(glocationSEQ.nextval,'	광주광역시	','	북구	')
 into glocation values(glocationSEQ.nextval,'	광주광역시	','	광산구	')
 into glocation values(glocationSEQ.nextval,'	대전광역시	','		')
 into glocation values(glocationSEQ.nextval,'	대전광역시	','	동구	')
 into glocation values(glocationSEQ.nextval,'	대전광역시	','	중구	')
 into glocation values(glocationSEQ.nextval,'	대전광역시	','	서구	')
 into glocation values(glocationSEQ.nextval,'	대전광역시	','	유성구	')
 into glocation values(glocationSEQ.nextval,'	대전광역시	','	대덕구	')
 into glocation values(glocationSEQ.nextval,'	울산광역시	','		')
 into glocation values(glocationSEQ.nextval,'	울산광역시	','	중구	')
 into glocation values(glocationSEQ.nextval,'	울산광역시	','	남구	')
 into glocation values(glocationSEQ.nextval,'	울산광역시	','	동구	')
 into glocation values(glocationSEQ.nextval,'	울산광역시	','	북구	')
 into glocation values(glocationSEQ.nextval,'	울산광역시	','	울주군	')
 into glocation values(glocationSEQ.nextval,'	세종특별자치시	','		')
 into glocation values(glocationSEQ.nextval,'	세종특별자치시	','	세종특별자치시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','		')
 into glocation values(glocationSEQ.nextval,'	경기도	','	수원시장안구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	수원시권선구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	수원시팔달구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	수원시영통구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	성남시수정구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	성남시중원구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	성남시분당구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	의정부시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	안양시만안구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	안양시동안구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	부천시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	광명시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	평택시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	동두천시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	안산시상록구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	안산시단원구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	고양시덕양구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	고양시일산동구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	고양시일산서구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	과천시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	구리시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	남양주시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	오산시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	시흥시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	군포시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	의왕시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	하남시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	용인시처인구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	용인시기흥구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	용인시수지구	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	파주시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	이천시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	안성시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	김포시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	화성시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	광주시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	양주시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	포천시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	여주시	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	연천군	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	가평군	')
 into glocation values(glocationSEQ.nextval,'	경기도	','	양평군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','		')
 into glocation values(glocationSEQ.nextval,'	강원도	','	춘천시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	원주시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	강릉시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	동해시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	태백시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	속초시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	삼척시	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	홍천군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	횡성군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	영월군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	평창군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	정선군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	철원군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	화천군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	양구군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	인제군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	고성군	')
 into glocation values(glocationSEQ.nextval,'	강원도	','	양양군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','		')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	청주시상당구	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	청주시서원구	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	청주시흥덕구	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	청주시청원구	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	충주시	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	제천시	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	보은군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	옥천군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	영동군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	증평군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	진천군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	괴산군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	음성군	')
 into glocation values(glocationSEQ.nextval,'	충청북도	','	단양군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','		')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	천안시동남구	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	천안시서북구	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	공주시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	보령시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	아산시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	서산시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	논산시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	계룡시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	당진시	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	금산군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	부여군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	서천군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	청양군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	홍성군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	예산군	')
 into glocation values(glocationSEQ.nextval,'	충청남도	','	태안군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','		')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	전주시완산구	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	전주시덕진구	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	군산시	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	익산시	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	정읍시	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	남원시	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	김제시	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	완주군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	진안군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	무주군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	장수군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	임실군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	순창군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	고창군	')
 into glocation values(glocationSEQ.nextval,'	전라북도	','	부안군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','		')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	목포시	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	여수시	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	순천시	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	나주시	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	광양시	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	담양군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	곡성군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	구례군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	고흥군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	보성군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	화순군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	장흥군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	강진군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	해남군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	영암군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	무안군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	함평군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	영광군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	장성군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	완도군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	진도군	')
 into glocation values(glocationSEQ.nextval,'	전라남도	','	신안군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','		')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	포항시남구	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	포항시북구	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	경주시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	김천시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	안동시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	구미시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	영주시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	영천시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	상주시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	문경시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	경산시	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	군위군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	의성군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	청송군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	영양군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	영덕군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	청도군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	고령군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	성주군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	칠곡군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	예천군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	봉화군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	울진군	')
 into glocation values(glocationSEQ.nextval,'	경상북도	','	울릉군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','		')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	창원시 의창구	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	창원시 성산구	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	창원시 마산합포구	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	창원시 마산회원구	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	창원시 진해구	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	진주시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	통영시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	사천시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	김해시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	밀양시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	거제시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	양산시	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	의령군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	함안군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	창녕군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	고성군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	남해군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	하동군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	산청군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	함양군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	거창군	')
 into glocation values(glocationSEQ.nextval,'	경상남도	','	합천군	')
 into glocation values(glocationSEQ.nextval,'	제주특별자치도	','		')
 into glocation values(glocationSEQ.nextval,'	제주특별자치도	','	제주시	')
 into glocation values(glocationSEQ.nextval,'	제주특별자치도	','	서귀포시	')
 into gage values(0,0)
 into gage values(1,10)
 into gage values(2,20)
 into gage values(3,30)
 into gage values(4,40)
 into gage values(5,50)
 into gage values(6,60)
 into gcategory values(gcategorySEQ.nextval,'게임')
 into gcategory values(gcategorySEQ.nextval,'연예/방송')
 into gcategory values(gcategorySEQ.nextval,'스포츠')
 into gcategory values(gcategorySEQ.nextval,'교육/금융/IT')
 into gcategory values(gcategorySEQ.nextval,'여행/음식/생물')
 into gcategory values(gcategorySEQ.nextval,'취미/생활')
 into gcategory2 values(gcategory2SEQ.nextval,1,'리그오브레전드')
 into gcategory2 values(gcategory2SEQ.nextval,1,'오버워치')
 into gcategory2 values(gcategory2SEQ.nextval,1,'바람의나라')
 into gcategory2 values(gcategory2SEQ.nextval,1,'카트라이더')
 into gcategory2 values(gcategory2SEQ.nextval,1,'테라')
 into gcategory2 values(gcategory2SEQ.nextval,1,'리니지')
 into gcategory2 values(gcategory2SEQ.nextval,2,'트와이스')
 into gcategory2 values(gcategory2SEQ.nextval,2,'태연')
 into gcategory2 values(gcategory2SEQ.nextval,2,'소녀시대')
 into gcategory2 values(gcategory2SEQ.nextval,2,'아이돌학교')
 into gcategory2 values(gcategory2SEQ.nextval,2,'스토브리그')
 into gcategory2 values(gcategory2SEQ.nextval,2,'도꺠비')
 into gcategory2 values(gcategory2SEQ.nextval,3,'야구')
 into gcategory2 values(gcategory2SEQ.nextval,3,'축구')
 into gcategory2 values(gcategory2SEQ.nextval,3,'자전거')
 into gcategory2 values(gcategory2SEQ.nextval,3,'수영')
 into gcategory2 values(gcategory2SEQ.nextval,3,'스키')
 into gcategory2 values(gcategory2SEQ.nextval,3,'볼링')
 into gcategory2 values(gcategory2SEQ.nextval,4,'공무원')
 into gcategory2 values(gcategory2SEQ.nextval,4,'편입')
 into gcategory2 values(gcategory2SEQ.nextval,4,'자격증')
 into gcategory2 values(gcategory2SEQ.nextval,4,'토익')
 into gcategory2 values(gcategory2SEQ.nextval,4,'증권')
 into gcategory2 values(gcategory2SEQ.nextval,4,'노트북')
 into gcategory2 values(gcategory2SEQ.nextval,5,'제주도')
 into gcategory2 values(gcategory2SEQ.nextval,5,'일본')
 into gcategory2 values(gcategory2SEQ.nextval,5,'중국')
 into gcategory2 values(gcategory2SEQ.nextval,5,'미국')
 into gcategory2 values(gcategory2SEQ.nextval,5,'치킨')
 into gcategory2 values(gcategory2SEQ.nextval,5,'피자')
 into gcategory2 values(gcategory2SEQ.nextval,6,'유투브')
 into gcategory2 values(gcategory2SEQ.nextval,6,'웹툰')
 into gcategory2 values(gcategory2SEQ.nextval,6,'만화')
 into gcategory2 values(gcategory2SEQ.nextval,6,'관상')
 into gcategory2 values(gcategory2SEQ.nextval,6,'사주')
/*관리자 계정*/ 
 into gusers values(0, 'admin','$2a$10$DGdkEZGSwAL1tOEmaEEqB.qfcKQrREhIo4wwgIfD5LWi/eICNg5Ha',
NULL,NULL,2,1,'F','plain64@naver.com',sysdate,'Y','N',0,null,0)
/*그룹 생성 시 같이 추가되어야함
 into ggroupboard values(1,1,'공지사항','Y','Y','Y','Y','Y','Y')
 into ggroupboard values(2,2,'공지사항','Y','Y','Y','Y','Y','Y')
*/
 SELECT *  FROM DUAL;
                                                 
                   
        
 
