insert into userpolice values(
nvl((select max(policekey) from userpolice)+1,0),
0, --신고한 유저
1,--글/댓글 여부
1,--글/댓글 번호
0,--욕/비방/정치/혐오
0--신고당한 유저
);

 // 모임게시글키값 
 private int postKey;

 // 제목 
 private String postTitle;

 // 내용 
 private String postContent;

 // 작성날짜 
 private Date postDate;

 // 모임키값 
 private int groupKey;

 // 유저키값 
 private int userKey;

 // 댓글허용여부 
 private String postOptionReply;

 // 검색허용여부 
 private String postOptionSearch;

 // 모임게시판키값 
 private int boardKey;

 // 조회수 
 private int postReadcount;

insert into Post values();






-- 고여니 테스트 ###############################
SELECT COUNT(USERKEY) FROM GGROUPMEMBER WHERE GROUPKEY = 3;  
SELECT * FROM GGROUPMEMBER WHERE GROUPKEY = 3;
SELECT * FROM GGROUPMEMBER;
SELECT * FROM GGROUP;

SELECT * FROM GGROUP WHERE GROUPKEY IN (SELECT GROUPKEY FROM GGROUPMEMBER WHERE USERKEY = 1); -- 회원수 조인해서 구해야 되는데.. 모르겠어 일단 보류 

SELECT * FROM POST;


-- 작성한 댓글
-- POST의 POSTTITLE, POSTCONTENT, POSTDATE를 받아오자..
SELECT POSTKEY, POSTTITLE, POSTCONTENT, POSTDATE
FROM POST
WHERE BOARDKEY IN (SELECT BOARDKEY
					FROM GGROUPBOARD
					WHERE GROUPKEY = #{GROUPKEY})

-- POSTKEY와 USERKEY에 해당하는 댓글 가져오기 
SELECT COMMENTCONTENT
FROM GCOMMENT
WHERE POSTKEY = #{POSTKEY} AND USERKEY = #{USERKEY}

INSERT INTO POST VALUES(postSEQ.NEXTVAL, '나는 바보야 페이지도 빨리 못 만드는 바보 ㅠ', '엉엉', sysdate, 2, 3, 'Y', 'Y', 2, 0);
INSERT INTO POST VALUES(postSEQ.NEXTVAL, '할 일이 많은데 속도가 안 붙어요', '바보죠?', sysdate, 2, 3, 'Y', 'Y', 2, 0);
INSERT INTO POST VALUES(postSEQ.NEXTVAL, '작성한 글은 뽑았는데 작성한 댓글은 못 뽑겠어..', '엉엉', sysdate, 2, 3, 'Y', 'Y', 2, 0);
INSERT INTO POST VALUES(postSEQ.NEXTVAL, '큰일났어요 큰일ㅇ났어..', 'ㅠㅠㅠㅠㅠㅠㅠㅠㅠ', sysdate, 2, 3, 'Y', 'Y', 2, 0);
INSERT INTO POST VALUES(postSEQ.NEXTVAL, '우와아앙오야양', '엉엉', sysdate, 2, 3, 'Y', 'Y', 2, 0);

SELECT * FROM POST WHERE USERKEY = 2 AND GROUPKEY = 3;

SELECT GROUPKEY, GROUPNAME, GROUPDFILE, TO_CHAR(GROUPDATE, 'YYYY-MM-DD') AS GROUPDATE, COUNT(*)
FROM ggroup
WHERE groupkey IN ( SELECT groupkey
					FROM ggroupmember
					WHERE userkey = 2)	
ORDER BY GROUPDATE DESC;			

-- 모임 조회 + 모임에 가입한 회원수
SELECT GROUPKEY, GROUPNAME, GROUPDFILE, GROUPDATE, USERKEY
FROM (	SELECT DISTINCT G.GROUPKEY AS GROUPKEY, G.GROUPNAME AS GROUPNAME, G.GROUPDFILE AS GROUPDFILE, G.GROUPDATE AS GROUPDATE, M.USERKEY
		FROM GGROUP G INNER JOIN GGROUPMEMBER M
		ON G.GROUPKEY = M.GROUPKEY
		ORDER BY GROUPKEY, USERKEY)
GROUP BY GROUPKEY
HAVING GROUPKEY IN (1, 3, 5);

-- 해당 회원이 참여하는 모임 목록
-- 각 모임들은 몇 명의 회원이 있는지 알아야 한다.
SELECT GROUPKEY, GROUPNAME, GROUPDFILE, TO_CHAR(GROUPDATE, 'YYYY-MM-DD') AS GROUPDATE, COUNT(GROUPKEY) AS MEMBERCOUNT
FROM (	SELECT G.GROUPKEY AS GROUPKEY, G.GROUPNAME AS GROUPNAME, G.GROUPDFILE AS GROUPDFILE, G.GROUPDATE AS GROUPDATE, M.USERKEY AS USERKEY
		FROM GGROUP G INNER JOIN GGROUPMEMBER M
		ON G.GROUPKEY = (SELECT GROUPKEY AS M.GROUPKEY FROM GGROUPMEMBER WHERE USERKEY = )
		ORDER BY GROUPKEY, USERKEY)
GROUP BY GROUPKEY, GROUPNAME, GROUPDFILE, GROUPDATE
HAVING USERKEY IN (2)
ORDER BY GROUPDATE DESC;


-- 그 모임들의 모임키, 모임명, 모임사진, 모임설립일, 회원수
SELECT GROUPKEY, COUNT(GROUPKEY) AS MEMBERCOUNT
FROM GGROUPMEMBER
GROUP BY GROUPKEY
HAVING GROUPKEY IN (SELECT GROUPKEY 
					FROM GGROUPMEMBER
					WHERE USERKEY = 2);
					
SELECT GROUPKEY, GROUPNAME, GROUPDFILE, TO_CHAR(GROUPDATE, 'YYYY-MM-DD') AS GROUPDATE, MEMBERCOUNT
FROM GGROUP NATURAL JOIN ( 	SELECT GROUPKEY, COUNT(GROUPKEY) AS MEMBERCOUNT
							FROM GGROUPMEMBER
							GROUP BY GROUPKEY
							HAVING GROUPKEY IN (SELECT GROUPKEY 
												FROM GGROUPMEMBER
												WHERE USERKEY = 2)) 
ORDER BY GROUPDATE DESC;



-- 작성한 댓글
